#!/usr/bin/python
#-*- coding: utf-8 -*-
#Copyright 2014 Clint Valentine & Darren Roscoe

"""
Each new term in the Fibonacci sequence is generated by adding the
previous two terms.

By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values
do not exceed four million, find the sum of the even-valued terms.
"""

from __future__ import print_function

ANSWER = 0

def fib(first=1, second=2):
    """Fibonacci generator function"""
    while 1:
        if first % 2 == 0:
            yield first
        if second > 4e6:
            break
        first, second = second, first + second

for i in fib():
    ANSWER += i

print(ANSWER)
